### ISSUE TITLE
Errors re: importing from node-only 'perf_hooks'

### ISSUE THREAD

**Issue by jfsiii** [RichiCoder1/opentelemetry-sdk-workers#18]
I tried installing in a current project that uses workers, and in a new one via https://workers.new/typescript They both failed but in different ways

I get these errors when I `npm i opentelemetry-sdk-workers` but they don't seem _too_ bad

```
npm WARN deprecated @opentelemetry/api-metrics@0.30.0: Please use @opentelemetry/api >= 1.3.0
npm WARN deprecated @opentelemetry/sdk-metrics-base@0.30.0: Please use @opentelemetry/sdk-metrics
```

<details><summary>local project (service worker format) failures</summary>

I see the `node` package is getting pulled in for some reason which then fails because the `node`-native package isn't available.

```
✘ [ERROR] Could not resolve "perf_hooks"

    ../../node_modules/@opentelemetry/core/build/esm/platform/node/performance.js:16:28:
      16 │ import { performance } from 'perf_hooks';
         ╵                             ~~~~~~~~~~~~

  The package "perf_hooks" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 ✘ [ERROR] Could not resolve "perf_hooks"

    ../../node_modules/@opentelemetry/otlp-exporter-base/node_modules/@opentelemetry/core/build/esm/platform/node/performance.js:16:28:
      16 │ import { performance } from 'perf_hooks';
         ╵                             ~~~~~~~~~~~~

  The package "perf_hooks" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 ✘ [ERROR] Could not resolve "perf_hooks"

    ../../node_modules/@opentelemetry/otlp-transformer/node_modules/@opentelemetry/core/build/esm/platform/node/performance.js:16:28:
      16 │ import { performance } from 'perf_hooks';
         ╵                             ~~~~~~~~~~~~

  The package "perf_hooks" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

 ✘ [ERROR] Could not resolve "perf_hooks"

    ../../node_modules/@opentelemetry/sdk-metrics-base/node_modules/@opentelemetry/core/build/esm/platform/node/performance.js:16:28:
      16 │ import { performance } from 'perf_hooks';
         ╵                             ~~~~~~~~~~~~

  The package "perf_hooks" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.


Build failed with 4 errors:
../../node_modules/@opentelemetry/core/build/esm/platform/node/performance.js:16:28: ERROR: Could not resolve "perf_hooks"
../../node_modules/@opentelemetry/otlp-exporter-base/node_modules/@opentelemetry/core/build/esm/platform/node/performance.js:16:28: ERROR: Could not resolve "perf_hooks"
../../node_modules/@opentelemetry/otlp-transformer/node_modules/@opentelemetry/core/build/esm/platform/node/performance.js:16:28: ERROR: Could not resolve "perf_hooks"
../../node_modules/@opentelemetry/sdk-metrics-base/node_modules/@opentelemetry/core/build/esm/platform/node/performance.js:16:28: ERROR: Could not resolve "perf_hooks"
Error
    at Object.onBuildFailure (/Users/jfsiii/work/mono-lift/node_modules/@remix-run/dev/dist/cli/commands.js:183:13)
    at buildEverything (/Users/jfsiii/work/mono-lift/node_modules/@remix-run/dev/dist/compiler.js:282:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.build (/Users/jfsiii/work/mono-lift/node_modules/@remix-run/dev/dist/compiler.js:102:3)
    at async Object.build (/Users/jfsiii/work/mono-lift/node_modules/@remix-run/dev/dist/cli/commands.js:178:3)
    at async Object.run (/Users/jfsiii/work/mono-lift/node_modules/@remix-run/dev/dist/cli/run.js:496:7)
```
</details>

<details><summary><del>failures</del> <ins>works</ins> on <a href="https://stackblitz.com/edit/cloudflare-templates-a8ep3p?file=src%2Findex.ts">stackblitz</a> (module worker format)</summary>

  Reading this more closely, I saw that it was failing b/c of the missing `performance` object, so I moved `import 'opentelemetry-sdk-workers/performance';` to the first line and everything was fine

  <details><summary>Initial failure</summary>
    This one seems to take a different route (no `node`)
    
    ```
    [mf:err] GET /: TypeError: Cannot read properties of undefined (reading 'timeOrigin')
        at getTimeOrigin (/home/projects/cloudflare-templatesa8ep3p/node_modules/@opentelemetry/core/src/common/time.ts:71:14)
        at timeInputToHrTime (/home/projects/cloudflare-templatesa8ep3p/node_modules/@opentelemetry/core/src/common/time.ts:112:15)
        at new Span2 (/home/projects/cloudflare-templates-a8ep3p/node_modules/@opentelemetry/sdk-tracebase/src/Span.ts:102:54)
        at Tracer2.startSpan (/home/projects/cloudflare-templates-a8ep3p/node_modules/@opentelemetry/sdk-tracebase/src/Tracer.ts:215:16)
        at _WorkersSDK.initSpan (/home/projects/cloudflare-templates-a8ep3p/node_modules/opentelemetry-sdk-workers/dist/index.mjs:371:28)
        at new _WorkersSDK (/home/projects/cloudflare-templates-a8ep3p/node_modules/opentelemetry-sdk-workers/dist/index.mjs:218:3)
        at Object.fetch (/home/projects/cloudflare-templates-a8ep3p/src/index.ts:26:14)
        at eval (/home/projects/cloudflare-templates-a8ep3p/node_modules/@miniflare/core/src/standards/event.ts:350:19)
        at eval (/home/projects/cloudflare-templates-a8ep3p/node_modules/@miniflare/shared/src/event.ts:29:9)
    ```
  </details>

</details>

Any idea what might be going on? Any thing I can do differently or to give more context for debugging?

On a somewhat related note, I've had some success with https://github.com/artifact-project/perf-tools/tree/master/performance and thought you might like it as inspiration / dependency for https://github.com/RichiCoder1/opentelemetry-sdk-workers/blob/main/packages/opentelemetry-sdk-workers/src/performance.ts

**Comment by jfsiii** [comment]
I now see that there have been some breaking changes (package renames among them) so these are probably a bigger deal than I realized.

```
npm WARN deprecated @opentelemetry/api-metrics@0.30.0: Please use @opentelemetry/api >= 1.3.0
npm WARN deprecated @opentelemetry/sdk-metrics-base@0.30.0: Please use @opentelemetry/sdk-metrics
```

I used npm `overrides` to use the latest versions of all the `@opentelemetry/*` packages and that got it down to 1 error

```
   ../../node_modules/@opentelemetry/core/build/esm/platform/node/performance.js:16:28:
      16 │ import { performance } from 'perf_hooks';
```

**Comment by RichiCoder1** [comment]
Yup, this is an unfortunate quirk of the fact that the base opentelemetry packages has no awareness or build for a "worker"-style platform. This project assumes one is using the standard Wrangler CLI for builds, and that build chain targets `"browser"`. That's why you also have to add the `import "opentelemetry-sdk-workers/performance";` as it polyfills a browser API that the otel libs assume exist but does not in Cloudflare Workers.

**Comment by jfsiii** [comment]
@RichiCoder1 Any idea what's this means on https://stackblitz.com/edit/cloudflare-templates-gdw8ku?file=src%2Findex.ts

```
Failed to flush spans: Error [OTLPExporterError]: Unknown error TypeError: fetch failed
    at new OTLPExporterError2 (/tmp/tmp-7-nrcs1fnjkIEn/index.js:3819:24)
    at eval (/tmp/tmp-7-nrcs1fnjkIEn/index.js:4134:13) {
  data: undefined,
  code: undefined
}
```

It says `fetch failed` but the `fetch` appears to succeed based on logs and the value shown on the screen. It seems like a runtime error in `opentelemetry-sdk-workers` but I can't say for sure

I'm happy to close this issue and have the discussion in another issue, discussion, etc. Just let me know. I get that this is a WIP but it's also _sooo_ useful and I really want to replace our homegrown one with yours 😄  Running on the edge with so little observability is killing me.

**Comment by jfsiii** [comment]
closed in favor of https://github.com/RichiCoder1/opentelemetry-sdk-workers/issues/19

**Comment by chrisvltn** [comment]
In case someone lands here again in the future.

For us, this library worked when using Remix in Cloudflare workers by changing Remix configuration to polyfill a few node modules:

```js
{
  // ...
  serverNodeBuiltinsPolyfill: {
    modules: [
      'os',
      'fs',
      'child_process',
      'stream',
      'zlib',
      'https',
      'http',
      'url',
      'perf_hooks',
      'buffer',
      'process',
    ],
    globals: {
      process: true,
      Buffer: true,
    },
  },
// ...
}
```

See here for more info: https://remix.run/docs/en/main/file-conventions/remix-config#servernodebuiltinspolyfill
